# Generated by Django 4.2.4 on 2023-08-17 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=50)),
                (
                    "status",
                    models.IntegerField(
                        default=1,
                        verbose_name=[
                            (1, "Created"),
                            (2, "Assigned"),
                            (3, "In Progress"),
                            (4, "Under review"),
                            (5, "Done"),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="users.team",
                    ),
                ),
            ],
        ),
    ]
