# Generated by Django 4.2.4 on 2023-08-17 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="user_id",
            field=models.ForeignKey(
                limit_choices_to={"role": ["0", "1"]},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
