# Generated by Django 4.2.4 on 2023-08-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_teammember_user_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("task_name", "team_id")},
        ),
    ]
