# Generated by Django 4.2.4 on 2023-08-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_teammember_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="team",
            name="unique__teamname_leaderid",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="user_id",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("role__in", ["0", "1"])),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("team_name", "leader_id")},
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team_id", "user_id")},
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="member_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="task_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.task"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskassignment",
            unique_together={("task_id", "member_id")},
        ),
    ]
